const fs = require('fs');
const path = require('path');

const indexPath = path.join(__dirname, '..', 'dist', 'build', 'index.html');

if (!fs.existsSync(indexPath)) {
  console.log('postbuild: index.html not found, skipping');
  process.exit(0);
}

let html = fs.readFileSync(indexPath, 'utf8');

// Remove "automatically generated by Strapi" HTML comment
html = html.replace(/<!--\s*\n?\s*This file was automatically generated by Strapi\.\s*\n?\s*Any modifications made will be discarded\.\s*\n?\s*-->\s*\n?/g, '');

// Replace page title
html = html.replace(/<title>Strapi Admin<\/title>/g, '<title>Content Metric</title>');

// Inject favicon link if not present
if (!html.includes('rel="icon"')) {
  html = html.replace('</title>', '</title><link rel="icon" type="image/png" href="/admin/favicon.png"/>');
}

fs.writeFileSync(indexPath, html, 'utf8');

// Copy favicon to build output
const faviconSrc = path.join(__dirname, '..', 'src', 'admin', 'extensions', 'favicon.png');
const faviconDest = path.join(__dirname, '..', 'dist', 'build', 'favicon.png');
if (fs.existsSync(faviconSrc)) {
  fs.copyFileSync(faviconSrc, faviconDest);
}

console.log('postbuild: Rebranded index.html');
