import { mergeConfig, type UserConfig } from 'vite';

export default (config: UserConfig) => {
  return mergeConfig(config, {
    server: {
      allowedHosts: true,
      port: Number(process.env.STRAPI_ADMIN_CLIENT_PORT) || undefined,
    },
    plugins: [
      {
        name: 'cm-rebrand',
        transformIndexHtml(html: string) {
          return html
            .replace(/<head>/, `<head><script>
(function(){
  var CD=30000,K='cm_chunk_reload';
  function ok(){var l=sessionStorage.getItem(K);return !l||Date.now()-Number(l)>CD}
  function go(){
    sessionStorage.setItem(K,String(Date.now()));
    var tries=0;
    (function poll(){
      fetch('/admin/',{method:'HEAD',cache:'no-store'}).then(function(r){
        if(r.ok)window.location.reload();
        else if(++tries<60)setTimeout(poll,3000);
      }).catch(function(){if(++tries<60)setTimeout(poll,3000)});
    })();
  }
  var P=['Failed to fetch dynamically imported module','Importing a module script failed',
    'error loading dynamically imported module','Failed to load module script','Load failed',
    'Something went wrong','bug in your instance','bug in the codebase','Unexpected Application Error'];
  new MutationObserver(function(m){
    for(var i=0;i<m.length;i++){var n=m[i].addedNodes;
      for(var j=0;j<n.length;j++){if(n[j].nodeType===1){var t=n[j].textContent||'';
        for(var k=0;k<P.length;k++){if(t.includes(P[k])){if(ok())go();return}}}}}
  }).observe(document.documentElement,{childList:true,subtree:true});
  var ce=console.error;
  console.error=function(){
    var a='';try{for(var i=0;i<arguments.length;i++){var v=arguments[i];a+=v instanceof Error?v.message:String(v)}}catch(e){}
    for(var k=0;k<P.length;k++){if(a.includes(P[k])){if(ok()){go();return}break}}
    ce.apply(console,arguments);
  };
  window.addEventListener('error',function(e){
    if(e.target&&(e.target.tagName==='SCRIPT'||e.target.tagName==='LINK')){
      var s=e.target.src||e.target.href||'';
      if((s.includes('/admin/')&&s.endsWith('.js'))||s.includes('/assets/'))if(ok())go()}
  },true);
  window.addEventListener('load',function(){
    var S=[];document.querySelectorAll('script[type="module"][src]').forEach(function(s){S.push(s.getAttribute('src'))});
    if(!S.length)return;
    function chk(){fetch('/admin/',{cache:'no-store'}).then(function(r){return r.ok?r.text():null}).then(function(h){
      if(!h)return;var v=false;for(var i=0;i<S.length;i++){if(h.indexOf(S[i])!==-1){v=true;break}}
      if(!v&&ok())go()}).catch(function(){})}
    setInterval(chk,15000);document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible')chk()})
  });
})();
</script>`)
            .replace(/<title>Strapi Admin<\/title>/, '<title>Content Metric</title>')
            .replace(
              /<!--\s*\n?\s*This file was automatically generated by Strapi\.\s*\n?\s*Any modifications made will be discarded\.\s*\n?\s*-->\s*\n?/g,
              ''
            )
            .replace(
              '</title>',
              '</title><link rel="icon" type="image/png" href="/admin/favicon.png"/>'
            );
        },
      },
    ],
  });
};
