import { mergeConfig, type UserConfig } from 'vite';

export default (config: UserConfig) => {
  return mergeConfig(config, {
    plugins: [
      {
        name: 'cm-rebrand',
        transformIndexHtml(html: string) {
          return html
            .replace(/<title>Strapi Admin<\/title>/, '<title>Content Metric</title>')
            .replace(
              /<!--\s*\n?\s*This file was automatically generated by Strapi\.\s*\n?\s*Any modifications made will be discarded\.\s*\n?\s*-->\s*\n?/g,
              ''
            )
            .replace(
              '</title>',
              '</title><link rel="icon" type="image/png" href="/admin/favicon.png"/>'
            );
        },
      },
    ],
  });
};
